### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by I-z-e-b-e-l** [Code-the-Dream-School/react-bald-eagle#39]
LOCATION OF ISSUE
What page/file is the issue on? 
(Example: Wiki, Lesson 2.1 or README.md)

https://github.com/Code-the-Dream-School/react-bald-eagle/wiki/Lesson-1.9

Where on that page/file is the issue locate?
(Example: paragraph 2 or "Familiarize yourself with the code" section)

Install React Router Section:
Read documentation: https://reactrouter.com/web/guides/quick-start

DESCRIPTION OF ISSUE
What type of issue is this?
(Example: typo, broken link, etc.)

broken link 

What is the issue?
(Example: Clicking the link to see the coding assignment for week 7 takes me to the wrong site or 404 error when clicking link, etc.)
leads to 404

**Comment by mamooredesigns** [comment]
Fixed!  Thanks for catching this :-)
